version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myapp_development
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp_password
    ports:
      - "3306:3306"

  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://myapp:myapp_password@db/myapp_development

  frontend: # サービス名
    build: # Dockerfileの設定
      context: . # Dockerfileを置いているディレクトリ
      dockerfile: Dockerfile.front # Dockerfileのファイル名
    working_dir: /frontend # 作業ディレクトリを指定
    volumes:
      - ./frontend:/frontend:cached
      # - node_modules:/frontend/node_modules

    tty: true # コンテナを正常終了するのを防ぐ
    ports:
      - "8080:5173" # 公開用のポート指定。ホスト側:コンテナ側
    command: sh -c "cd frontend && npm run dev --host" # viteの実行コマンド

volumes:
  db-data:
  # node_modules:
